### ISSUE TITLE
Slider: range variant causes 1px shift in track

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#1527]
### Expected Behaviour

Variants should not alter position of slider elements

### Actual Behaviour

Using the `range` variant causes a 1px shift in the track position. 

You can see it explicitly between these two stories:

* https://cuberoot-multi-handle-slider--spectrum-web-components.netlify.app/storybook/index.html?path=/story/slider--two-handles
* https://cuberoot-multi-handle-slider--spectrum-web-components.netlify.app/storybook/index.html?path=/story/slider--three-handles-ordered

The track travels up 1px moving between the first and the second story, seemingly due to the variant attribute being moved to range between the two. This seems to be due to the way that margin is applied in this rule:

```css
:host([dir="ltr"][variant="range"]) .track,
:host([dir="rtl"][variant="range"]) .track {
    padding-top: 0px;
    padding-bottom: 0px;
    padding-left: var(--spectrum-slider-track-middle-handleoffset);
    padding-right: var(--spectrum-slider-track-middle-handleoffset);
    margin: var(--spectrum-slider-range-track-reset);
}
```

Which applies margin-top: 0; and overrides the "standard" or expected styling in:

```css
#fill, 
.track {
    height: var(--spectrum-slider-track-height);
    box-sizing: border-box;
    position: absolute;
    z-index: 1;
    top: calc(var(--spectrum-slider-height)/2);
    margin-top: calc(var(--spectrum-slider-track-height)/-2);
    pointer-events: none;
}
```

#### Steps to Reproduce

Compare stories that add use `variant=range` to those that don't

* https://cuberoot-multi-handle-slider--spectrum-web-components.netlify.app/storybook/index.html?path=/story/slider--two-handles
* https://cuberoot-multi-handle-slider--spectrum-web-components.netlify.app/storybook/index.html?path=/story/slider--three-handles-ordered
