### ISSUE TITLE
Ignore Visual Diffing when merging to master?

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#328]
We should be able to skip this with:
```
- visual-testing:
    branches:
      ignore:
        - master
    requires:
      - build
```
Doing so would prevent `master` from going red on flaky test passes and reduce the CI burden that comes with visual testing the same code more than once. The down side is likely that we would want to be more strict about having PR branches be up-to-date before allowing the merge so that we know 100% the code on both sides of the PR is the same.

Thoughts?

**Comment by Westbrook** [comment]
We've recently moved to have the CI pass for the `master` branch be how we freshen the cache on the golden images to ensure they don't expire (30 day TTL) in Circle. This could technically be mitigated by using _any_ passing branch to freshen the cache and then to gate the visual regressions by branch to prevent `master` from running them like:
```
            - visual-lightest-medium:
                  branches:
                      ignore:
                          - master
                  requires:
                      - build
            - visual-lightest-large:
                  branches:
                      ignore:
                          - master
                  requires:
                      - build
            - visual-light-medium:
                  branches:
                      ignore:
                          - master
                  requires:
                      - build
            - visual-light-large:
                  branches:
                      ignore:
                          - master
                  requires:
                      - build
            - visual-dark-medium:
                  branches:
                      ignore:
                          - master
                  requires:
                      - build
            - visual-dark-large:
                  branches:
                      ignore:
                          - master
                  requires:
                      - build
```

This feels a little less pressing now that we have a better handle on the test flakiness, so I'll leave this here for a little while more before deciding whether to pursue or close this.
