### ISSUE TITLE
[Bug]: Blocker: Overlay/Tooltip flickering and positioning issues on Safari

### ISSUE THREAD

**Issue by jonathandannel** [adobe/spectrum-web-components#5420]
### Code of conduct

- [x] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay, Tooltip

### Expected behavior

We have various SWC`Tooltip` elements wrapped in `Overlay` elements to achieve the following behavior:
- Using the x, y offset of the Overlay to customize the positioning of the tooltips
- Using the delayed Overlay to properly delay non-self-managed tooltips
- Using the type: ‘auto’ on the Overlay to close the tooltip on interaction with the anchor element

### Actual behavior

In Safari, there is a very jarring flicker where the Overlay/Tooltip appears in a totally different (fixed) location when one Overlay closes and another one opens. 

I’m not able to find a property or CSS override that has any effect on this behavior. I have also tried moving the overlays around to different areas of the DOM to no avail. 

The Overlay/Tooltip combo is necessary for our use case, outlined above, and this bugin Safari is blocking us from releasing the feature.

### Screenshots

https://github.com/user-attachments/assets/cc7020e9-ec54-4ea0-9666-8ebe1834b0a1

https://github.com/user-attachments/assets/f47422d3-92c5-4cd6-b81e-2cf2c5695109

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

Our application components look like the following:
```tsx
 return (
    <Overlay
      type="auto"
      data-testid="studio-rich-tooltip-overlay"
      receivesFocus="false"
      placement={props.placement}
      delayed={props.delayed ?? true}
      {...overlayWrapperConfig}
    >
      <RichTooltip
        {...props}
        selfManaged={false}
        description={t(props.description)}
        keybind={props.keybind ? t(props.keybind) : undefined}
        offsetPx={offsetPxByUISize?.[sizePreference] || props.offsetPx}
        title={t(props.title)}
      />
    </Overlay>
  )
```

```tsx
  <Tooltip
      data-testid="rich-tooltip-tooltip"
      delayed={delayed}
      slot={slot}
      selfManaged={selfManaged}
      placement={placement}
      offset={selfManaged ? offsetPx : undefined}
      className={styles['rich-tooltip']}
      style={
        {
          '--mod-tooltip-margin': selfManaged ? undefined : `${offsetPx}px`
        } as React.CSSProperties
      }
    >
...
```

```css
rich-tooltip {
  --mod-tooltip-spacing-inline: 0px;
  --mod-tooltip-max-inline-size: 500px;
  --mod-tooltip-tip-block-size: 0px;
  --mod-tooltip-tip-square-size: 0px;
  --mod-tooltip-spacing-block-start: 0px;
  --mod-tooltip-spacing-block-end: 0px;
  --mod-overlay-animation-duration: 0s;
  --mod-tooltip-background-color-default: rgba(0, 0, 0, 0);
  --mod-tooltip-animation-distance: 0px;
}
```

### Sample code or abstract reproduction which illustrates the problem

Interactive sandbox: https://studio.webcomponents.dev/edit/r98dYS9yAje977XKtrxD/src/index.ts?p=stories

In the sandbox, the issue only happens intermittently and when there’s a transform/translate on the parent element. In our app, it happens 100% of the time, sometimes with a translate property but other times without, always on Safari and never on Chrome.

### Severity

SEV 2
